### ISSUE TITLE
Cannot run blinky

### ISSUE THREAD

**Issue by lukamac** [fusesoc/blinky#40]
Hi!

I wanted to try out fusesoc (since I heard so many great things about it) and got stuck at running blinky :(

I have a PYNQ_Z1 board and it is basically the same as PYNQ_Z2 that is supported already in the blinky project. For some reason, when i try to run it with
```
$ fusesoc run --target=pynq_z2 fusesoc:utils:blinky
```
I get
```
ERROR: No tool was supplied on command line or found in 'fusesoc:utils:blinky' core description
```
which is weird since PYNQ_Z2 has default_tool defined to vivado.

Then I added the `--tool=vivado` option
```
$ fusesoc run --tool=vivado --target=pynq_z2 fusesoc:utils:blinky
```
but I got another error
```
ERROR: Failed to determine work root. Could not resolve target
```

Could you please help me.

**Comment by olofk** [comment]
Sorry to hear it's not working out of the box, and thanks for reporting so we can hopefully fix it.

I don't know right away whay the problem is, but I have a feeling that the error message is a bit misleading. Can you start by runninh `fusesoc core show fusesoc:utils:blinky` to ensure that the core is found and that there is a target with the name you specified?

**Comment by lukamac** [comment]
I have done it and among other targets there is PYNQ_Z2:
```
pynq_z2                        : Pynq-Z2 Zynq Z7020 Evaluation Kit
```

**Comment by lukamac** [comment]
Hi!
Just updated fusesoc to 1.11.0 and edalize to 0.2.3 and it works now :)

**Comment by olofk** [comment]
Fantastic. Happy to hear it worked out eventually. Still a bit annoyed that I have absolutely no idea what the problem was before but let's forget about that
